### ISSUE TITLE
Multi choice question: Option labels cut off

### ISSUE THREAD

**Issue by jobenjada** [formbricks/snoopforms#84]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The answer text of a multiple choice question is cut off after 3-4 words

### Steps to Reproduce

![grafik](https://user-images.githubusercontent.com/72809645/191111377-88e7b3ab-388a-480d-8fa4-941df46128c0.png)

## Environment

- [ ] snoopForms Cloud (app.snoopforms.com)

### Additional Context

(Write your answer here.)

**Comment by matthiasnannt** [comment]
fixed with 6ae4566baf2abafd0d72224edc75384fd9f30b2d
